In [1]:
import pandas as pd

In [2]:
# extract datasets
df_male_players = pd.read_csv('data/FIFA-dataset/male_players.csv')
# df_male_teams = pd.read_csv('data/FIFA-dataset/male_teams.csv')
# df_male_coaches = pd.read_csv('data/FIFA-dataset/male_coaches.csv')

In [5]:
# df = df_male_players.loc[(df_male_players.fifa_version>23) & (df_male_players.league_name.isin()),:]
# print(df_male_players.league_name.unique())
# print(df.head())
# print(df.shape)
leagues = ["Premier League", 'Jupiler Pro League', "Bundesliga",'3. Liga', "Serie A", "La Liga", "Ligue 1", "Eredivisie",
            'Championship', 'La Liga 2', 'Serie B', '2. Bundesliga', 'Ligue 2', 'Liga Portugal', 'Super Lig', 'Major League Soccer']
for league in leagues:
    df = df_male_players.loc[(df_male_players.fifa_version>23) & (df_male_players.league_name.isin([league])),:]
    # print(df_male_players.league_name.unique())
    # print(df.head())
    print(df.shape)


(679, 109)
(426, 109)
(850, 109)
(537, 109)
(842, 109)
(596, 109)
(500, 109)
(501, 109)
(696, 109)
(611, 109)


(546, 109)
(513, 109)
(540, 109)
(496, 109)
(544, 109)
(841, 109)


In [51]:
print("Overall Players: " + str(len(df_male_players)))
df_male_players = df_male_players[df_male_players['fifa_version'] == 24]
print("Players in 24: " + str(len(df_male_players)))

Overall Players: 180021
Players in 24: 18350


In [52]:
print("Overall Teams: " + str(len(df_male_teams)))
df_male_teams = df_male_teams[df_male_teams['fifa_version'] == 24]
print("Teams in 24: " + str(len(df_male_teams)))

Overall Teams: 6947
Teams in 24: 702


In [53]:
print("Overall Coaches: " + str(len(df_male_coaches)))

Overall Coaches: 1369


In [59]:
# check for correlating attributes in teams and players
common_columns_players_teams = set(df_male_players.columns).intersection(set(df_male_teams.columns))
print(common_columns_players_teams)

common_columns_players_teams_coaches = common_columns_players_teams = set(df_male_players.columns).intersection(set(df_male_teams.columns)).intersection(set(df_male_coaches))
print(common_columns_players_teams_coaches)

{'update_as_of', 'nationality_name', 'nationality_id', 'fifa_update', 'league_id', 'overall', 'league_level', 'fifa_version', 'league_name'}
{'nationality_name'}


### Merging tables: 
- players <-> teams: players.club_name <-> teams.name 
- coaches <-> teams: teams.coach_id <-> coaches.id



In [55]:
players_teams_merged = pd.merge(df_male_players, df_male_teams, left_on='club_name', right_on='team_name', how='left')
final_merged_dataframe = pd.merge(players_teams_merged, df_male_coaches, left_on='team_id', right_on='coach_id', how='left')

final_merged_dataframe.drop(['club_name', 'team_name', 'team_id'], axis=1, inplace=True)

In [56]:
final_merged_dataframe

player_id                                         player_url   
0          18115  /player/18115/ruben-miguel-santos-fernandes/24...  \
1          19541                  /player/19541/glenn-morris/240002   
2          20801   /player/20801/c-ronaldo-dos-santos-aveiro/240002   
3          23823             /player/23823/andreas-johansson/240002   
4          24630        /player/24630/jose-manuel-reina-paez/240002   
...          ...                                                ...   
18447     278132               /player/278132/rakan-al-kaabi/240002   
18448     278138                   /player/278138/josh-keyes/240002   
18449     278139               /player/278139/rodrigo-frutos/240002   
18450     278141                /player/278141/christian-bos/240002   
18451     278145     /player/278145/shahruddin-magomedaliyev/240002   

       fifa_version_x  fifa_update_x update_as_of_x       short_name_x   
0                24.0            2.0     2023-09-22    Rúben Fernandes  \
1                24.0            2.0     2023-09-22          G. Morris   
2                24.0            2.0     2023-09-22  Cristiano Ronaldo   
3                24.0            2.0     2023-09-22       A. Johansson   
4                24.0            2.0     2023-09-22         Pepe Reina   
...               ...            ...            ...                ...   
18447            24.0            2.0     2023-09-22        R. Al Kaabi   
18448            24.0            2.0     2023-09-22           J. Keyes   
18449            24.0            2.0     2023-09-22          R. Frutos   
18450            24.0            2.0     2023-09-22             C. Bos   
18451            24.0            2.0     2023-09-22   S. Magomedaliyev   

                                     long_name_x player_positions  overall_x   
0      Rúben Miguel Marques dos Santos Fernandes               CB         71  \
1                             Glenn James Morris               GK         62   
2            Cristiano Ronaldo dos Santos Aveiro               ST         86   
3                   Karl Tommy Andreas Johansson               CB         65   
4                         José Manuel Reina Páez               GK         77   
...                                          ...              ...        ...   
18447                             Rakan Al Kaabi          CDM, CM         54   
18448                                 Josh Keyes               CM         51   
18449                             Rodrigo Frutos               GK         58   
18450                              Christian Bos               RB         55   
18451                   Shahruddin Magomedaliyev               GK         70   

       potential  ...  chance_creation_shooting  chance_creation_positioning   
0             71  ...                       NaN                          NaN  \
1             62  ...                       NaN                          NaN   
2             86  ...                       NaN                          NaN   
3             65  ...                       NaN                          NaN   
4             77  ...                       NaN                          NaN   
...          ...  ...                       ...                          ...   
18447         66  ...                       NaN                          NaN   
18448         65  ...                       NaN                          NaN   
18449         66  ...                       NaN                          NaN   
18450         70  ...                       NaN                          NaN   
18451         71  ...                       NaN                          NaN   

       coach_id_y coach_url  short_name_y  long_name_y  dob_y   
0             NaN       NaN           NaN          NaN    NaN  \
1             NaN       NaN           NaN          NaN    NaN   
2             NaN       NaN           NaN          NaN    NaN   
3             NaN       NaN           NaN          NaN    NaN   
4             NaN 

1. 3 different data sets [X]

2.  at least 2,500 entities described in total (in joint dataset) − but more are better, good: >10,000 but <100,000 (18452) [X]

3.  at least 1,000 entities should be contained in at least two datasets (Players: 18350, Coaches: 1369, Teams: 702) [X]

4. at least 8 attributes in joint dataset (168) [X]

5. at least 5 attributes should be contained in at least two datasets (Players: 109, Coaches: 8, Teams: 54) [X] some attributes (other than name) should be contained in three datasets (for fusion by voting): 1. -> nationality_by_name

6. Ideally, at least one of your attributes is a list attribute (Players: player_positions, player_traits) [X]